# fly.toml app configuration file generated for job-watcher on 2025-08-02T16:14:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-watcher'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256

[env]
  DB_PATH = "/data/job-watcher.db"
  LOG_PATH = "/data/job-watcher.log"

[mounts]
  source = "jobwatcher_data"
  destination = "/data"
