name: Curl GET with secret

on:
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    env:
      REFRESH_URL: ${{ secrets.REFRESH_URL }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    steps:
      - name: Mask token just in case
        run: echo "::add-mask::$REFRESH_TOKEN"
      - name: GET request with Authorization header
        run: |
          curl -sSfL -G "$REFRESH_URL" \
            -H "Authorization: Bearer $REFRESH_TOKEN"
